[package]
name = "t-app"
version = "0.1.0"
authors = ["Mark Aiken <gwmaiken@att.net>"]

[dependencies]
futures = "0.1.14"
hyper = "0.11.2"
tokio-core = "0.1"
serde_json = "1.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser","psapi","processthreadsapi"] }